
let initState={
    customerMsg:[
        {
            id:1,
            title:"web移动app项目",
            time:"14个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:2,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:3,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:4,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:5,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:6,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:7,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:8,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:9,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },
        {
            id:10,
            title:"web移动app项目",
            time:"10个月",
            description:"这个项目是一个移动app项目电商类商品",
            standard:"利用react和ant-design框架",
            customer:"前端工程师",
            inviter:"小溪流",
            weight:50,
            public:"部分公开"
        },

    ]
}

export default (state=initState,action)=>{
    let newState = JSON.parse(JSON.stringify(state))
    return newState

} 